[Challenge Tourial] Fix the compilation error
1. lose precision error caused by 'Env.Students.size()'
2. lib\host\host_function_example\examplefunc.cpp(46,42) : error :'[' tokens introducing attribute are separated by whitespace [-Werror,-Wcompound-token-split-by-space]